### ISSUE TITLE
SLS Offline DynamoDB Streams: Several issues referencing DynamoDB table streams

### ISSUE THREAD

**Issue by cwienands1** [CoorpAcademy/serverless-plugins#103]
I am using SLS Offline DynamoDB Streams (SODS) to develop and test a Serverless + NodeJS application that uses DynamoDB streams to trigger additional Lambda functions. I have struggled with specifying the ARN of the DynamoDB stream correctly and during that course found several issues around this.

Issue 1: At the very bottom of the [SODS NPM page](https://www.npmjs.com/package/serverless-offline-dynamodb-streams) an example describes a variant using a _tableName_ key. This does work and from all I can tell is also not supported by the [_getTableName_](https://github.com/CoorpAcademy/serverless-plugins/blob/master/packages/serverless-offline-dynamodb-streams/src/index.js#L180) function.

Issue 2: [Line 186 of index.js](https://github.com/CoorpAcademy/serverless-plugins/blob/master/packages/serverless-offline-dynamodb-streams/src/index.js#L186) is missing an additional null check for _arn_:
`if (tableEvent.arn && tableEvent.arn['Fn::GetAtt']) {`

Issue 3: I did not test this but from all I can tell, there are two more ways to [specify a DynamoDB table stream in Serverless](https://serverless.com/framework/docs/providers/aws/events/streams/) that are not supported by SODS:
```
      - stream:
          type: dynamodb
          arn:
            Fn::ImportValue: MyExportedDynamoDbStreamArnId
      - stream:
          type: dynamodb
          arn:
            Ref: MyDynamoDbTableStreamArn
```
It could be that those two ways are not feasible for local deployments (again, I didn't test them) but I figured I'll point it out anyway.
