### ISSUE TITLE
SQS Offline - MalformedQueryString

### ISSUE THREAD

**Issue by esetnik** [CoorpAcademy/serverless-plugins#111]
After upgrading from v3.0.1 to v3.1.1 I get an error MalformedQueryString. It looks like the RedrivePolicy might be the problem, although this config was previously working and also matches the serverless documentation.

```
    EmailQueue:
      Type: AWS::SQS::Queue
      Properties:
        QueueName: queue-name-${self:provider.stage}
        MessageRetentionPeriod: 1209600
        RedrivePolicy:
          deadLetterTargetArn:
            'Fn::GetAtt':
              - EmailDeadLetterQueue
              - Arn
          maxReceiveCount: 5
```

Logs:
```
**Serverless: [AWS sqs 400 0.546s 0 retries] createQueue({
  QueueName: 'queue-name-local',
  Attributes: {
    MessageRetentionPeriod: '1209600',
    RedrivePolicy: '[object Object]'
  }
})

  Malformed Query String ---------------------------------

  MalformedQueryString: MalformedQueryString; see the SQS docs.
      at Request.extractError (/app/node_modules/aws-sdk/lib/protocol/query.js:50:29)
      at Request.callListeners (/app/node_modules/aws-sdk/lib/sequential_executor.js:106:20)
      at Request.emit (/app/node_modules/aws-sdk/lib/sequential_executor.js:78:10)
      at Request.emit (/app/node_modules/aws-sdk/lib/request.js:683:14)
      at Request.transition (/app/node_modules/aws-sdk/lib/request.js:22:10)
      at AcceptorStateMachine.runTo (/app/node_modules/aws-sdk/lib/state_machine.js:14:12)
      at /app/node_modules/aws-sdk/lib/state_machine.js:26:10
      at Request.<anonymous> (/app/node_modules/aws-sdk/lib/request.js:38:9)
      at Request.<anonymous> (/app/node_modules/aws-sdk/lib/request.js:685:12)
      at Request.callListeners (/app/node_modules/aws-sdk/lib/sequential_executor.js:116:18)
      at Request.emit (/app/node_modules/aws-sdk/lib/sequential_executor.js:78:10)
      at Request.emit (/app/node_modules/aws-sdk/lib/request.js:683:14)
      at Request.transition (/app/node_modules/aws-sdk/lib/request.js:22:10)
      at AcceptorStateMachine.runTo (/app/node_modules/aws-sdk/lib/state_machine.js:14:12)
      at /app/node_modules/aws-sdk/lib/state_machine.js:26:10
      at Request.<anonymous> (/app/node_modules/aws-sdk/lib/request.js:38:9)
      at Request.<anonymous> (/app/node_modules/aws-sdk/lib/request.js:685:12)
      at Request.callListeners (/app/node_modules/aws-sdk/lib/sequential_executor.js:116:18)
      at callNextListener (/app/node_modules/aws-sdk/lib/sequential_executor.js:96:12)
      at IncomingMessage.onEnd (/app/node_modules/aws-sdk/lib/event_listeners.js:307:13)
      at IncomingMessage.emit (events.js:215:7)
      at IncomingMessage.EventEmitter.emit (domain.js:475:20)
      at endReadableNT (_stream_readable.js:1184:12)
      at processTicksAndRejections (internal/process/task_queues.js:80:21)
```
