### ISSUE TITLE
[serverless-offline-sqs] Doesn't trigger lambda on new events

### ISSUE THREAD

**Issue by comtom** [CoorpAcademy/serverless-plugins#118]
Bear in mind the following lambda definition:

```
sqs_triggered_lambda:
  handler: function.handle
  events:
    - sqs:
        arn:
          Fn::GetAtt:
            - QueueName
            - Arn
```

When a new message arrives the queue, it won't execute the lambda function locally (within serverless-offline).

**Comment by AdrieanKhisbe** [comment]
@comtom can you send the whole _(redacted)_ serverless config?

The part of config you sent imply there would be some 

```
resources:
  Resources:
    QueueName:
      Type: AWS::SQS::Queue
      Properties:
        QueueName: your-queue-name
```

Is that the case?

**Comment by comtom** [comment]
Correct, I have this:

`Resources:
  QueueName:
    Type: "AWS::SQS::Queue"
    Properties:
      QueueName: QueueName
      VisibilityTimeout: 30
      MessageRetentionPeriod: 1209600
`

the setup works correctly in AWS but not with serverless-ofline-sqs.
Is something wrong in these configs?

**Comment by AdrieanKhisbe** [comment]
I think I got why, Queue creation is not done by default by `serverless-offline-sqs`

you need to activate it with option `autoCreate: true` and have a sqs localy running:

you find more details in the Configuration SQS section of the README: 
https://github.com/CoorpAcademy/serverless-plugins/tree/master/packages/serverless-offline-sqs#sqs

**Comment by comtom** [comment]
hey, I've tried that without success, I debugged the plugin and the  issue seems to be at `serverless-offline-sqs/src/index.js:211`

`client.getQueueUrl({QueueName}, cb)` call is raising an exception.

If change the line to `const { QueueUrl } = await fromCallback(cb => `http://localhost:9324/queue/${QueueName}`);` does not throw the exception below.

This is the error I'm getting:
`
  A W S. Simple Queue Service. Non Existent Queue --------
 
  AWS.SimpleQueueService.NonExistentQueue: The specified queue does not exist for this wsdl version.
      at Request.extractError (/home/comtom/Projects/electric/api-middleware/node_modules/aws-sdk/lib/protocol/query.js:50:29)
      at Request.callListeners (/home/comtom/Projects/electric/api-middleware/node_modules/aws-sdk/lib/sequential_executor.js:106:20)
      at Request.emit (/home/comtom/Projects/electric/api-middleware/node_modules/aws-sdk/lib/sequential_executor.js:78:10)
      at Request.emit (/home/comtom/Projects/electric/api-middleware/node_modules/aws-sdk/lib/request.js:683:14)
      at Request.transition (/home/comtom/Projects/electric/api-middleware/node_modules/aws-sdk/lib/request.js:22:10)
      at AcceptorStateMachine.runTo (/home/comtom/Projects/electric/api-middleware/node_modules/aws-sdk/lib/state_machine.js:14:12)
      at /home/comtom/Projects/electric/api-middleware/node_modules/aws-sdk/lib/state_machine.js:26:10
      at Request.<anonymous> (/home/comtom/Projects/electric/api-middleware/node_modules/aws-sdk/lib/request.js:38:9)
      at Request.<anonymous> (/home/comtom/Projects/electric/api-middleware/node_modules/aws-sdk/lib/request.js:685:12)
      at Request.callListeners (/home/comtom/Projects/electric/api-middleware/node_modules/aws-sdk/lib/sequential_executor.js:116:18)
      at Request.emit (/home/comtom/Projects/electric/api-middleware/node_modules/aws-sdk/lib/sequential_executor.js:78:10)
      at Request.emit (/home/comtom/Projects/electric/api-middleware/node_modules/aws-sdk/lib/request.js:683:14)
      at Request.transition (/home/comtom/Projects/electric/api-middleware/node_modules/aws-sdk/lib/request.js:22:10)
      at AcceptorStateMachine.runTo (/home/comtom/Projects/electric/api-middleware/node_modules/aws-sdk/lib/state_machine.js:14:12)
      at /home/comtom/Projects/electric/api-middleware/node_modules/aws-sdk/lib/state_machine.js:26:10
      at Request.<anonymous> (/home/comtom/Projects/electric/api-middleware/node_modules/aws-sdk/lib/request.js:38:9)
      at Request.<anonymous> (/home/comtom/Projects/electric/api-middleware/node_modules/aws-sdk/lib/request.js:685:12)
      at Request.callListeners (/home/comtom/Projects/electric/api-middleware/node_modules/aws-sdk/lib/sequential_executor.js:116:18)
      at callNextListener (/home/comtom/Projects/electric/api-middleware/node_modules/aws-sdk/lib/sequential_executor.js:96:12)
      at IncomingMessage.onEnd (/home/comtom/Projects/electric/api-middleware/node_modules/aws-sdk/lib/event_listeners.js:307:13)
      at IncomingMessage.emit (events.js:203:15)
      at IncomingMessage.EventEmitter.emit (domain.js:448:20)
      at endReadableNT (_stream_readable.js:1145:12)
      at process._tickCallback (internal/process/next_tick.js:63:19)
 
     For debugging logs, run again after setting the "SLS_DEBUG=*" environment variable.
 
  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues
     Issues:        forum.serverless.com
 
  Your Environment Information ---------------------------
     Operating System:          linux
     Node Version:              10.19.0
     Framework Version:         1.67.0
     Plugin Version:            3.6.3
     SDK Version:               2.3.0
     Components Version:        2.27.0

`

**Comment by comtom** [comment]
Found that the config block was incorrectly indented. Now is working perfectly!!!

I think perhaps adding an error saying that the config is not there could be helpful. Thanks for your support :)

**Comment by natac13** [comment]
@comtom How so? I am experiencing the same error message but cannot find why my config is wrong. Especially after I just copied it from the docs lol.

**Comment by visrut-at-handldigital** [comment]
I am facing the same error, but I have everything double-checked

```yml
custom:
  esbuild:
    bundle: true
    minify: false
    sourcemap: linked
    keepNames: true
    watch:
      pattern:
        - 'functions/**/*.ts'
        - 'functions/**/*.js'
  serverless-offline:
    httpPort: 4000
    prefix: 'http'
    useChildProcesses: true
    lambdaPort: 5000
  serverless-offline-sqs:
    autoCreate: true
    apiVersion: '2012-11-05'
    endpoint: http://0.0.0.0:9324
    region: us-east-2
    accessKeyId: root
    secretAccessKey: root
    skipCacheInvalidation: false

resources:
  - Resources:
      MyTaskQueue:
        Type: AWS::SQS::Queue
        Properties:
          QueueName: mytask.fifo
          FifoQueue: true
          ContentBasedDeduplication: true
          VisibilityTimeout: 900 # Set this to match the Lambda function timeout
    Outputs:
      MyTaskQueueUrl:
        Value:
          Ref: MyTaskQueue
        Export:
          Name: MyTaskQueueUrl

functions:
  sqsReportGenerator:
    handler: functions/sqs-report-generator.handler
    events:
      - sqs:
          arn:
            Fn::GetAtt:
              - MyTaskQueue
              - Arn
          batchSize: 1
```

I have also checked if the queue is created or not, despite setting `autoCreate: true`, it was not created when I was starting the offline server, so I manually created it using the below commands

```yml
aws sqs list-queues --endpoint-url http://localhost:9324 --region us-east-2
aws sqs create-queue --queue-name mytask.fifo --attributes FifoQueue=true,ContentBasedDeduplication=true --endpoint-url http://localhost:9324 --region us-east-2
```

The message is also coming when I send it using function
```ts

const sqs = new SQSClient({
  region: process.env.AWS_DEFAULT_REGION,

  endpoint: "http://localhost:9324",
  credentials: {
    accessKeyId: "root",
    secretAccessKey: "root",
  },
});

const handler = () => {
  const command = new SendMessageCommand({
    QueueUrl: "http://localhost:9324/queue/mytask.fifo",
    MessageBody: JSON.stringify({
      ...data,
    }),
    MessageGroupId: `group-{data.id}`,
    MessageDeduplicationId: data.id,
  });
  
  await sqs.send(command);
}
```

![Image](https://github.com/user-attachments/assets/81c5f1b6-18fd-4b04-8ea6-a2a6f9ac987e)

but it does not trigger the `sqsReportGenerator` lambda somehow
