### ISSUE TITLE
serverless-offline-sqs - receiving frequent  503: Service Unavailable

### ISSUE THREAD

**Issue by zoellner** [CoorpAcademy/serverless-plugins#123]
change made by @esetnik in https://github.com/CoorpAcademy/serverless-plugins/commit/40efaf96244d52668d4a2580cbca314e9109d05b seems to be the cause. 
Setting the timeout to the maximum value ends up with frequent timeouts. Lower numbers work fine

**Comment by esetnik** [comment]
@zoellner any idea why this is the case? AWS specifies 20s as the maximum allowable WaitTimeSeconds and I use this in my projects without any issues.

**Comment by zoellner** [comment]
I'm not quite sure yet.
It might be related to this https://github.com/softwaremill/elasticmq/issues/9
Although they claim that it is fixed on their end

My `serverless-offline-sqs` config is 
```
  serverless-offline-sqs:
    # port and AWS creds need to match command in package.json
    autoCreate: false
    apiVersion: '2012-11-05'
    endpoint: http://127.0.0.1:9324
    region: us-east-1
    accessKeyId: root
    secretAccessKey: root
    skipCacheInvalidation: false
```

using `softwaremill/elasticmq:latest` docker image for local SQS
