### ISSUE TITLE
Queue auto-creation works only if a function has an attached sqs trigger

### ISSUE THREAD

**Issue by Saka7** [CoorpAcademy/serverless-plugins#124]
Queue auto-creation works only if there is an `sqs` trigger in the function configuration:

e.g.
```yaml
functions:
  mySQSHandler:
    handler: handler.compute
    events:
      - sqs: arn:aws:sqs:region:XXXXXX:MyFirstQueue
```
[source code link](https://github.com/CoorpAcademy/serverless-plugins/blob/fc19ef6d8a10bde712adf7b95f0ede3fa673a0d8/packages/serverless-offline-sqs/src/index.js#L266)

What if a lambda-function should work as a publisher and does not have `sqs` event trigger (e.g. listens on `http` event and pushes items into the queue)?

**Suggestion**: Maybe it's better to create queues based on a `resources` property?
