### ISSUE TITLE
serverless-offline-sqs - SQS and HTTP events

### ISSUE THREAD

**Issue by manniniandrea** [CoorpAcademy/serverless-plugins#132]
Hello,

I'm trying to make this configuration work:

```yaml
...
plugins:
  ...
  - serverless-offline-sqs #@4.0.1
  - serverless-offline #@6.4.0
custom:
  ...
  serverless-offline-sqs:
    autoCreate: true
    apiVersion: '2012-11-05'
    endpoint: http://localhost:9324
    region: eu-west-1
    accessKeyId: root
    secretAccessKey: root
    skipCacheInvalidation: false
provider:
  name: aws
  runtime: nodejs12.x
  region: eu-west-1
  ...
functions:
  main:
    handler: src/handlers/any.handler
    memorySize: 256
    events:
      - http:
          method: any
          path: /{any+}
          cors: true
  job:
    handler: src/handlers/job.handler
    memorySize: 256
    events:
      - sqs:
          arn:
            Fn::GetAtt:
              - MainQueue
              - Arn
resources:
  Resources:
    MainQueue:
      Type: "AWS::SQS::Queue"
      Properties:
        QueueName: "MainQueue"
```

Unfortunately, when i run the project, only one of the two lambda works.. what i mean is, if i run the project without the SQS plugins, the "http" lambda correctly starts up and i can make http calls at it, but when i start the project with the SQS plugin, only the SQS lambda correctly starts. Im unable to make them both work at the same time, any help?
