### ISSUE TITLE
serverless-offline-sqs: unable to use output from queue as an environment variable

### ISSUE THREAD

**Issue by matthewelwell** [CoorpAcademy/serverless-plugins#135]
I'm trying to configure an SQS queue and output the queue's url as an environment variable to be consumed by other lambda functions, however, whatever I try, the environment variable is simply being set as `[object Object]`. 

I've tried multiple ways of setting the environment variable but from what I can tell the following should work: 

```
# serverless.yml 

service: sqs-test

plugins:
  - serverless-offline-sqs
  - serverless-offline

provider:
  name: aws
  runtime: python3.7
  environment:
    QUEUE_URL: { Ref: MyQueue }
    ANOTHER_ENVIRONMENT_VARIABLE: "test"

functions:
  mySQSHandler:
    handler: handler.sqs_handler
    events:
      - sqs:
          arn:
            Fn::GetAtt:
              - MyQueue
              - Arn

  myAPIGWHandler:
    handler: handler.api_handler
    events:
      - http:
          method: get
          path: /test


custom:
  serverless-offline-sqs:
    autoCreate: true                 # create queue if not exists
    apiVersion: '2012-11-05'
    endpoint: http://0.0.0.0:9324
    region: eu-west-1
    accessKeyId: root
    secretAccessKey: root
    skipCacheInvalidation: false


resources:
  Resources:
    MyQueue:
      Type: AWS::SQS::Queue
      Properties:
        QueueName: MyQueue

```

```
# handler.py

import json
import logging
import os

logger = logging.getLogger(__name__)
logger.setLevel(logging.DEBUG)


def api_handler(event, context):
    logger.debug("Handling request from API gateway.")
    response = {
        "QUEUE_URL": os.environ["QUEUE_URL"],
        "ANOTHER_ENVIRONMENT_VARIABLE": os.environ["ANOTHER_ENVIRONMENT_VARIABLE"]
    }
    return {
        "body": json.dumps(response),
        "statusCode": 200
    }


def sqs_handler(event, context):
    logger.debug("Handling request from SQS.")


```

If I deploy the above to AWS then I can see that the QUEUE_URL environment variable parameter gets set correctly, however, when I run it locally, the environment variable appears to just be set as "[object Object]", as can be seen using the test endpoint that I've included in the sample application above. 

Perhaps this is a serverless-offline issue rather than a serverless-offline-sqs issue, however, you might be able to point me to another way to get the queue URL into an environment variable?
