### ISSUE TITLE
Serverless offline sqs stop trigger event 

### ISSUE THREAD

**Issue by drizzef** [CoorpAcademy/serverless-plugins#147]
Hi,

We are working with a serverless offline SQS plugin and we didn't notice what we did but in offline mode, the lambda stops triggering when there is a message on the queue(we are using Elasicmq on the local environment).

this is the YAML file:

    ```
app: xxxxx-micro-services
    service: microservices
    
    provider:
      name: aws
      runtime: nodejs12.x
      stage: ${opt:stage, 'dev'}
      region: eu-west-1
      iamRoleStatements:
        - Effect: "Allow"
          Action:
            - "sqs:SendMessage"
            - "sqs:GetQueueUrl"
          Resource:
            Fn::GetAtt:
              - EmailsQueue
              - Arn
        - Effect: "Allow"
          Action:
            - "sqs:ListQueues"
          Resource:
            Fn::GetAtt:
              - EmailsQueue
              - Arn
    
    functions:
      emailProducer:
        handler: src/handler.emailProducer
        events:
          - http:
              path: /email
              method: post
        environment:
          DEFAULT_FROM_EMAIL: ${self:custom.email.defaultAddress}
          EMAILS_QUEUE_URL: ${self:custom.queue.email.url}
          EMAILS_ACCESS_KEY_ID: ${self:custom.queue.email.accessKeyId}
          EMAILS_SECERT_ACCESS_KEY: ${self:custom.queue.email.secretAccessKey}
          EMAILS_REGION: ${self:custom.queue.email.region}
      emailConsumer:
        handler: src/handler.emailConsumer
        environment:
          NODE_ENV: ${self:custom.env}
          EMAIL_SMTP_USER_NAME: ${self:custom.email.smtp.userName}
          EMAIL_SMTP_PASSWORD: ${self:custom.email.smtp.password}
        events:
          - sqs:
              arn:
                Fn::GetAtt:
                  - EmailsQueue
                  - Arn
    
    plugins:
      - serverless-plugin-typescript
      - serverless-offline
      - serverless-offline-sqs
    
    resources:
      Resources:
        EmailsQueue:
          Type: AWS::SQS::Queue
          Properties:
            QueueName: emails
    
    custom: ${file(${opt:stage, self:provider.stage, 'dev'}.config.yml)}
```

the dev.config.yaml, we include it in the custom block.

    ```
env: test
    email:
      smtp:
        userName: fdsfdsf@dasd.cc
        password: 123456
      defaultAddress: fdfsdfsdf@cc.cc
    queue:
      email:
        region: eu-west-1
        accessKeyId: root
        secretAccessKey: root
        url: http://localhost:9324/queue/emails
    serverless-offline:
      httpPort: 4400
    serverless-offline-sqs:
      autoCreate: true # create queue if not exists
      apiVersion: "2012-11-05"
      endpoint: http://0.0.0.0:9324
      region: eu-west-1
      accessKeyId: root
      secretAccessKey: root
      skipCacheInvalidation: false
```
