### ISSUE TITLE
local .ssm values are being read into serverless-state.json on serverless deploy to AWS

### ISSUE THREAD

**Issue by bitsofinfo** [CoorpAcademy/serverless-plugins#151]
serverless 2.12.0
serverless-offline@6.8.0
serverless-offline-ssm-provider@2.1.0

app's serverless.yml
```
plugins:
  - serverless-offline-ssm-provider
  - serverless-plugin-scripts
  - serverless-offline

...

provider:
  name: aws
  runtime: python3.8
  environment:
    LOG_LEVEL: DEBUG
    MY_API_KEY: ${ssm:/aws/reference/secretsmanager/my-api-key~true}
```

my .ssm file
```
/aws/reference/secretsmanager/my-api-key=123
```

`my-api-key` exists as a secret in the SSM parameter store in AWS. When I deploy I expect that value to be consumed, not the value in the `.ssm` file which as I understand is only when running in local serverless offline mode.

Why is it when I run `serverless deploy --stage dev` I end up w/ the `serverless-offline-ssm-provider` sourced secrets from the local `.ssm` dumped into my `serverless-state.json` .... the result of this is that my actual secrets in SSM in AWS are not being used, instead, the function is deployed in lambda sourcing the values from the lambda ENV which was populated on deploy from my local secrets in `.ssm`

.serverless/serverless-state.json
```
{
  "service": {
    "service": "test1",
    "serviceObject": {
      "name": "test1"
    },
    "provider": {
      "name": "aws",
      "runtime": "python3.8",
      "environment": {
        "LOG_LEVEL": "DEBUG",
        "MY_API_KEY": "123"
      },
....
```

Pre `serverless deploy ...` if I manually MOVE the `.ssm` file, then it works
