### ISSUE TITLE
ReadCountOutOfRange; see the SQS docs w/ sqs.batchSize > 1

### ISSUE THREAD

**Issue by bitsofinfo** [CoorpAcademy/serverless-plugins#165]
Running serverless 2.19.0 offline w/ ` "serverless-offline-sqs": "4.1.1",`

```
      - sqs: 
          arn: <myqueuearn>
          batchSize: 50
          maximumBatchingWindow: 30
```

```
Serverless: [AWS sqs 400 0.152s 0 retries] receiveMessage({
  QueueUrl: 'http://localhost:9324/queue/my-queue',
  MaxNumberOfMessages: 50,
  AttributeNames: [ 'All', [length]: 1 ],
  MessageAttributeNames: [ 'All', [length]: 1 ],
  WaitTimeSeconds: 5
})
 
  Read Count Out Of Range --------------------------------
 
  ReadCountOutOfRange: ReadCountOutOfRange; see the SQS docs.

```
