### ISSUE TITLE
[serverless-offline-sqs] Missing Query Param Rejection( Queue Name), Missing Form Field Rejection( Queue Url)

### ISSUE THREAD

**Issue by nicolaspfernandes** [CoorpAcademy/serverless-plugins#189]
Hi!

I'm having troubles with putting some serverless functions running together with `serverless-offline-sqs` package within a Docker container. Whenever I start my container, it recognizes the queues, mount my functions, but suddenly this error appears:

![image](https://user-images.githubusercontent.com/7490993/127007367-b9691d11-3cd1-475c-8742-624d6b514d36.png)

Tried to find any useful information on the docs, but couldn't find any.
Am I missing something? Thanks for the help!

`serverless-offline-sqs` config:
```
serverless-offline-sqs:
    autoCreate: false
    apiVersion: "2012-11-05"
    endpoint: http://elasticmq:9324
    region: some-region
    accessKeyId: some-acccess-key
    secretAccessKey: some-secret-access-key
    skipCacheInvalidation: false
```

My queue name for a dev environment is custom configured as:
```
  sqs-queue-name:
    dev: "arn:aws:sqs:some-region:root:QueueName.fifo"
```

`elastic.conf` is done like this:

```
queues {
    QueueName {
        defaultVisibilityTimeout = 10 seconds
        delay = 1 seconds
        receiveMessageWait = 0 seconds
        fifo = true
        contentBasedDeduplication = true    
    }
}
```
