### ISSUE TITLE
Suggestion: Auto creation

### ISSUE THREAD

**Issue by freitasmurillo** [CoorpAcademy/serverless-plugins#19]
@godu 

Currently the sqs plugin doesn't create the queues declared at resources.
Maybe we could add this feature?
I made a [PR](https://github.com/godu/serverless/pull/15) as a suggestion.
It try to create the queue only using the queue name. If the queue already exists nothing changes.

**Comment by sebmor** [comment]
As a reference, this is a fork https://github.com/msfidelis/serverless-offline-sqs-esmq which added this

**Comment by freitasmurillo** [comment]
@sebmor can you add the link in the pull request as well?

**Comment by theogravity** [comment]
@sebmor thanks for that - it works!

**Comment by godu** [comment]
Merged ! Good work 👍

**Comment by godu** [comment]
```yaml
custom:
  serverless-offline-sqs:
    autoCreate: true                 # create queue if not exists
```
