### ISSUE TITLE
variablesResolutionMode: 20210326 breaks this plugin

### ISSUE THREAD

**Issue by haneyman** [CoorpAcademy/serverless-plugins#195]
variablesResolutionMode: 20210326 seems to be required in order to properly package and deploy to AWS.

Unfortunately it seems to break this plugin when running offline, any alternatives or resolutions?
Error:
  Cannot resolve serverless.yml: Variables resolution errored with:
    - Cannot resolve variable at "provider.environment.STRIPE_API_KEY": An error occurred while calling one AWS dependency service.,
    - Cannot resolve variable at "provider.environment.STRIPE_SIGNING_SECRET": An error occurred while calling one AWS dependency service.

**Comment by luiz-bonfioli-syngenta** [comment]
I have the same problem and the serverless documentation is not good enough.

**Comment by eddie-atkinson** [comment]
+1 I am also experiencing this issue. Not sure what the remedy is?

**Comment by silouone** [comment]
Thanks for the report @haneyman! This one is the Serverless variable resolver itself trying to reach real AWS SSM for `provider.environment` rather than anything in `serverless-offline-ssm-provider` — with `variablesResolutionMode: 20210326`, offline resolution of `${ssm:...}` is handled differently, so wiring those values through this plugin's `.ssm` file (or moving them out of `provider.environment` for the offline stage) is the way to keep both packaging and offline working. Happy to help dig into your exact config if you can share the relevant `provider.environment` block. 🙏

**Comment by silouone** [comment]
Thanks for the report @haneyman, and for the confirmations @luiz-bonfioli-syngenta and @eddie-atkinson.

The error here comes from the **Serverless Framework's own variable resolver**, not from this plugin. With `variablesResolutionMode: 20210326`, the framework eagerly resolves `${ssm:...}` references — including those in `provider.environment` — by calling **real AWS SSM** up front, which is why `STRIPE_API_KEY` / `STRIPE_SIGNING_SECRET` fail with `An error occurred while calling one AWS dependency service` when you have no live AWS access offline.

The good news is that `serverless-offline-ssm-provider` is built to handle exactly this. It patches the `aws` provider's `request` method and intercepts `('SSM', 'getParameter', …)` for your configured offline stages, so it works **regardless of `variablesResolutionMode`** — the interception happens at the provider-request layer the built-in resolver ultimately calls.

To make both packaging and offline work, declare the values in the plugin's **local map** (note: an inline map under `custom.serverless-offline-ssm`, not a `.ssm` file):

```yml
plugins:
  - serverless-offline-ssm-provider
  - serverless-offline

custom:
  serverless-offline-ssm:
    stages:
      - offline
      - dev
    ssm:
      /path/to/stripe-api-key: sk_test_xxx
      /path/to/stripe-signing-secret: whsec_xxx

provider:
  environment:
    STRIPE_API_KEY: ${ssm:/path/to/stripe-api-key}
    STRIPE_SIGNING_SECRET: ${ssm:/path/to/stripe-signing-secret}
```

On your configured offline stages those `${ssm:...}` lookups resolve from the local map with zero AWS round-trips; on real deploy stages the plugin never patches anything, so packaging/deploy still hit real SSM as before.

Since the breakage is in core-serverless resolution rather than this plugin, I'll close this as answered — but I'm very happy to dig into your exact `provider.environment` block if the local-map approach doesn't resolve it for you, so feel free to reopen with the config. 🙏
