### ISSUE TITLE
[serverless-offline-sqs] Missing QueueName

### ISSUE THREAD

**Issue by jlgouwyapizr** [CoorpAcademy/serverless-plugins#200]
Hey folks, 

On my side, still have [this issue](https://github.com/CoorpAcademy/serverless-plugins/issues/5#issuecomment-646893597) : 
```
Missing required key 'QueueName' in params
```

I'm using the SDK v3. The last version of serverless offline and offline-sqs.
the serverless-offline-sqs is loaded after serverless-offline. 

here is my definition : 
```
    events:
      - sqs:
          arn: { "Fn::Join" : [":", ["arn:aws:sqs:${self:provider.region}", { "Ref" : "AWS::AccountId" }, "${self:provider.stage}-salesforce-customers-update"]]  }
          batchSize: 1
```

In the SQSEventDefinition file, when we receive the rawSqsEventDefinition , here is the result : 
```
{"arn":{"Fn::Join":[":",["arn:aws:sqs:eu-west-1",{"Ref":"AWS::AccountId"},"local-salesforce-customers-update"]]},"batchSize":1}
```

The type is object. So it falls to : 
```
if (typeof rawSqsEventDefinition !== 'string') {
      Object.assign(this, omit(['arn', 'queueName', 'enabled'], rawSqsEventDefinition));
}
```

Which returns : 
```
SQSEventDefinition {
  enabled: true,
  arn: 'arn:aws:sqs:eu-west-1:000000000000:undefined',
  queueName: undefined,
  batchSize: 1
}
```

So it isn't able to extract correctly. 

thanks

**Comment by thetumper** [comment]
Having similar issue.  Also, not sure why queueName is required?  Serverless gives me a warning about it, but serverless-offline-sqs seems to require it.  If I remove, serverless is happy, but then the event does not trigger.

**Comment by alex88** [comment]
Same here, I'm trying to use it with serverless-lift and I have the same error, not sure why it's using AWS sdk to create the queue

**Comment by plcharriere** [comment]
Same issue here, even when using the serverless configuration example.

**Comment by gk1041** [comment]
Has there been any progress on this issue?

**Comment by sandyscoffable** [comment]
+1 using lift

**Comment by serg06** [comment]
Hey all, I just wrote a guide for solving this issue (see above), hope it helps!

**Comment by akfreas** [comment]
For me, the issue was having two queues in the `arn:` property.
```
    events:
      - sqs:
          arn:
            !GetAtt MessagingQueue.Arn
            !GetAtt MessagingInternalQueue.Arn
```

I fixed it by just adding another `- sqs` event below the first one.

**Comment by WNC-Travis** [comment]
Digging into the source code:
https://github.com/CoorpAcademy/serverless-plugins/blob/master/packages/serverless-offline-sqs/src/sqs.js#L85
has `queueName` as a child of `sqs` and at the same level as `arn`.

Something like this got me past this error:

```
    events:
      - sqs:
          queueName: "MyQueueName"
          arn: { "Fn::Join" : [":", ["arn:aws:sqs:${self:provider.region}", { "Ref" : "AWS::AccountId" }, "${self:provider.stage}-salesforce-customers-update"]]  }
          batchSize: 1
```
