### ISSUE TITLE
sqs does not work in combination with normal http events

### ISSUE THREAD

**Issue by sambP** [CoorpAcademy/serverless-plugins#202]
I'm not able to get serverless-offline-sqs working in combination with "normal" HTTP lambdas. After adding the plugin in the serverless.yml, serverless offline does not start the HTTP server anymore. But the sqs triggered lambda is working great. Do I miss something here?

My versions:
```
    "serverless": "2.66.2",
    "serverless-offline": "8.2.0",
    "serverless-offline-sqs": "6.0.0",
```

serverless.yml
```
plugins:
  - serverless-webpack
  - serverless-offline-sqs
  - serverless-offline

custom:
  serverless-offline-sqs:
    autoCreate: false
    apiVersion: '2012-11-05'
    endpoint: http://0.0.0.0:9324
    region: ${self:provider.region}
    accessKeyId: root
    secretAccessKey: root
    skipCacheInvalidation: false

functions:
  httpsLambda:
    name: x
    handler: x
    events:
      - http:
          path: /x
          method: post

  sqsLambda:
    name: y
    handler: y
    events:
      - sqs:
          arn: arn:aws:sqs:${self:provider.region}:${self:custom.accountId}:${self:custom.queue}
          batchSize: 1

resources:
  Resources:
    queue:
      Type: AWS::SQS::Queue
      Properties:
        QueueName: ${self:custom.queue}
        VisibilityTimeout: 300 # 5min
        ContentBasedDeduplication: true
```
