### ISSUE TITLE
Guide for setting up serverless-offline-sqs + serverless-lift + localstack sqs

### ISSUE THREAD

**Issue by serg06** [CoorpAcademy/serverless-plugins#239]
# Guide for setting up serverless-offline-sqs + serverless-lift + localstack sqs

I just spent the last few hours figuring this out, so I'll share my solution with you all.

Disclaimer: This guide is only for sls offline. It likely needs modification before deploying.

Disclaimer: You will have to modify `serverless-offline-sqs` as it doesn't work with `lift` by default.

### Set up the SQS server

```bash
# Install Python and Docker beforehand

# Install CLI tools if you don't have them
pip install awscli  # `aws`
pip install awscli-local  # `awslocal`

# Start localstack
docker run -p 4566:4566 -d --restart unless-stopped localstack/localstack

# Create the queue locally
AWS_DEFAULT_REGION=us-east-2 awslocal sqs create-queue --queue-name myQueue --attributes "FifoQueue=false"

# Get the queue's ARN for later
AWS_DEFAULT_REGION=us-east-2 awslocal sqs get-queue-attributes --queue-url 'http://localhost:4566/000000000000/myQueue' --attribute-names QueueArn
```

### Install the Node packages:

```
yarn add @aws-sdk/client-sqs
yarn add -D serverless-offline-sqs serverless-lift @types/aws-lambda
```

### Set up your serverless.yaml

```yaml
plugins:
  ...
  - serverless-lift
  - serverless-offline-sqs  # MUST BE ABOVE serverless-offline OR ELSE IT WON'T WORK
  - serverless-offline
  ...

constructs:
  myQueue:
    type: queue
    fifo: false
    worker:
      handler: src/functions/myQueue.handler

provider:
  environment:
    ...
    MY_QUEUE_URL: ${construct:myQueue.queueUrl}

custom:
  serverless-offline-sqs:
    autoCreate: false  # We already created it
    region: us-east-2
    endpoint: http://localhost:4566
    apiVersion: '2012-11-05'
    accessKeyId: foobar  # localstack auth
    secretAccessKey: foobar  # localstack auth
    queueName: myQueue  # required for lift support, not supported by default but we'll fix that
```

### Set up your publisher

```ts
import {SQSClient} from '@aws-sdk/client-sqs';
import {SendMessageCommand} from '@aws-sdk/client-sqs';

export const sqs = new SQSClient({
    region: 'us-east-2',
    endpoint: 'http://localhost:4566'
});

// Somewhere else in the code...
console.log('Publishing event...');
await userCacheQueueClient.send(new SendMessageCommand({
    MessageBody: '{"hello": "there"}',
    QueueUrl: 'myQueue'
}));
```

### Set up your consumer

```ts
import {SQSBatchResponse, SQSEvent} from 'aws-lambda/trigger/sqs';
import {writeFileSync} from 'fs';

void import('source-map-support/register');  // Optional but recommended

async function server(event: SQSEvent, context: Record<string, unknown>): Promise<void | {} | SQSBatchResponse> {
    console.log('Consuming event...');
    console.log({event});
    return {};
}

module.exports.handler = server;
```

### Patch serverless-offline-sqs:

This plugin has had issues with lift since forever:
- https://github.com/CoorpAcademy/serverless-plugins/issues/5
- https://github.com/CoorpAcademy/serverless-plugins/issues/200
- https://github.com/getlift/lift/issues/109

In order to fix that, you need to apply a patch:
- https://github.com/CoorpAcademy/serverless-plugins/pull/211

Ideally you'd apply that patch in your `postinstall` script, but you can do it manually too.

### Test it out
```
sls offline --verbose --useInProcess
```
