### ISSUE TITLE
[serverless-offline-sqs] Doesn't trigger lambda when new message is added to elasticMQ

### ISSUE THREAD

**Issue by 10Bude10** [CoorpAcademy/serverless-plugins#255]
**Expect:**
When a new message is added to elasticMQ my responsible lambda is triggered for handling the message

**Current behaviour:**
Lambda sends messages to local SQS queue. The running elasticMQ displays received messages. The responsible lambda to handle SQS messages isn't triggered.

**Setup:**
package.json
```
"@aws-sdk/client-sqs": "^3.354.0",
"serverless-esbuild": "^1.46.0",
"serverless-offline": "^12.0.4",
"serverless-offline-sqs": "^7.3.2",
```
serverless.yml
```
serverless-offline-sqs:
    autoCreate: false
    endpoint: http://localhost:9324
    region: ${self:provider.region}
    accessKeyId: root
    secretAccessKey: root
    skipCacheInvalidation: false
    apiVersion: '2012-11-05'

plugins:
  - serverless-esbuild
  - serverless-offline
  - serverless-offline-sqs

functions:
  addIndustryData:
      handler: src/handler/industry/handler.addIndustryData
      events:
        - sqs:
            arn:
              Ref: fetchIndustryDataQueue

resources:
  Resources:
    fetchIndustryDataQueue:
      Type: AWS::SQS::Queue
      Properties:
        QueueName: fetchIndustryDataQueue
```

custom.conf (for elasticMQ)
```
include classpath("application.conf")
queues {
  fetchIndustryDataQueue {
    defaultVisibilityTimeout = 30 seconds
    delay = 0 seconds
    receiveMessageWait = 0 seconds
  }
}
# Region and accountId which will be included in resource ids
aws {
  region = eu-central-1
  accountId = root
}
```
Any ideas, what's the problem that the lambda isn't triggered?
