### ISSUE TITLE
Question: SQS offline package

### ISSUE THREAD

**Issue by alexbeletsky** [CoorpAcademy/serverless-plugins#29]
Sorry, it could be a very basic question, but README.md of `sqs-offline` is very short and doesn't explain much. 

I want to use the package for local development and I thought that plugin emulates the queue behavior. It's already mentioned in this issue https://github.com/godu/serverless/issues/9 that you have to have some "real" queue to be running to make it work. 

The proposed solution is to run ElasicMQ locally or inside a Docker container. 

An example is very helpful, but I can see it uses `aws-sdk` to `create-queue`.. my question is where actually those queues are created? In AWS or somehow locally?

Would be happy to clarify those questions and update README, so it's more clear for a people like me :)

/cc @Maxwell2022

**Comment by Maxwell2022** [comment]
Hi Alex, 

Yes, I understand it's confusing, I'm not the author of this great plugin but I can try to explain how it works. Firstly to address your concern on `create-queue` you' notice that it target `localhost` and not an AWS URL or ARN. 

What you need to know is, localhost queue URLs target your local queue and any AWS URL target the actual SQS queue. Here is a sample of my `docker-compose` config that is setting up the queue (locally). We use docker-compose for our local development in order to simulate the AWS, that is the only goal of Docker here, simulate AWS infrastructure.

```
version: '3'
services:
  sqs:
    container_name: local_sqs_1
    image: s12v/elasticmq:latest
    ports:
      - 9324:9324
  sqs-create:
    container_name: create_local_sqs_queue_1
    image: infrastructureascode/aws-cli:latest
    links:
      - sqs
    entrypoint: sh
    volumes:
      - ./sqs/create-queues.sh:/project/create-queues.sh:ro
    environment:
      - AWS_ACCESS_KEY_ID=$SQS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY=$SQS_SECRET_ACCESS_KEY
      - AWS_ENDPOINT_URL=$SQS_ENDPOINT_URL
    command: './create-queues.sh'
```

There are 2 services declared here, the first one is `sqs` using `s12v/elasticmq:latest` that is simulating the AWS SQS wrapping the service with RabbitMQ I think. This service understands the AWS command and executes them inside its container (create-queue, poll queue, etc...) So you can use the `aws sqs [...]` commands, targetting this queue and it would work. Note that we map the ports `9324:9324` so that we can access it using `localhost` from any other container.

The second service `sqs-create` is just a helper script to create the SQS queue inside the container we just started above. As you can see it's `link`ed to it because we'll need to have network access to it. This container that creates the queue is using `infrastructureascode/aws-cli:latest` Dcoker image which gives us access to the `aws sqs [...]` command inside this container, to create our queues. Once this service start, it runs the given command that is actually creating the queue locally, in our sqs container and once it's done, it stopped.

Then you should have your application container, running whatever version of node you want, mounting your app inside, setting the env variables (AWS one for instance). This application service in your docker-compose has to be linked to the sqs container.

In your serverless config:

```
plugins:
  - ...
  - serverless-offline-sqs

serverless-offline-sqs:
    apiVersion: '2012-11-05'
    endpoint: http://sqs:9324
    region: ${env:AWS_DEFAULT_REGION}
    accessKeyId: root
    secretAccessKey: root
```

Note that the hostname of the queue is the name of the docker-compose service, in our case `sqs`.

I hope this help
