### ISSUE TITLE
endpoint is resolving to 127.0.0.1

### ISSUE THREAD

**Issue by rpedretti** [CoorpAcademy/serverless-plugins#33]
I have a docker for my lambda and for the sqs, with this compose file:
```
version: "3.7"
services: 
  sqs:
    image: softwaremill/elasticmq:0.14.6
    volumes: 
      - ./env/mq.conf:/opt/elasticmq.conf
    ports:
      - "9324:9324"
  lambda:
    image: softinstigate/serverless
    volumes:
      - <path to source>:/lambda
      - ~/.aws/:/root/.aws/
    working_dir: /lambda
    tty: true
    entrypoint: bash
    command: -c "npm run debug"
```

my serverless.yml has the following config:
```
serverless-offline-sqs:
    endpoint: http://sqs:9324
    region: us-east-1
    accessKeyId: root
    secretAccessKey: root
    skipCacheInvalidation: false
```

But my lambda tries to connect to 127.0.0.1:

```
lambda_1  | (node:16) UnhandledPromiseRejectionWarning: Error: connect ECONNREFUSED 127.0.0.1:9324
```

If i try some random IP thats not mapped on my host or containers the IP is resolve to that random IP.

I'm running docker on Windows:

Docker version 18.09.1, build 4c52b90
docker-compose version 1.23.2, build 1110ad01

**Comment by godu** [comment]
@rpedretti You should use [`depends_on` attribute](https://docs.docker.com/compose/compose-file/#depends_on).

In my company, we use this :

- `docker-compose.test.yml`
```yaml
version: '3.4'
services:
  kinesis:
    image: coorpacademy/kinesalite
    ports:
      - 4567:4567

  sut:
    build:
      context: .
      target: test
      args:
        NODE_ENV: test
    command: [ "test" ]
    environment:
      KINESIS_ENDPOINT: "http://kinesis:4567"
    depends_on:
      - kinesis
    volumes:
      - ./test:/app/src/test
```

- `serverless.yml`
```yaml
  serverless-offline-kinesis:
    endpoint: ${env:KINESIS_ENDPOINT, 'http://0.0.0.0:4567'}
    region: eu-west-1
    accessKeyId: local
    secretAccessKey: local
    skipCacheInvalidation: ${env:SKIP_CACHE_INVALIDATION}
    readInterval: ${env:READ_INTERVAL, "500"}
```
