### ISSUE TITLE
SQS Offline configuration error

### ISSUE THREAD

**Issue by jaffacake** [CoorpAcademy/serverless-plugins#56]
Hi, I'm using the latest version of the offline sqs plugin and it is throwing an error when attempting to `sqs offline start`

```
(node:16897) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'arn' of null
    at ServerlessOfflineSQS.getQueueName (/Users/xxxx/code/authoriser/node_modules/serverless-offline-sqs/src/index.js:68:27)
    at ServerlessOfflineSQS.createQueueReadable (/Users/xxxx/code/authoriser/node_modules/serverless-offline-sqs/src/index.js:160:28)
```

This is part of my serverless file:
```yaml

custom:
  queueName: 'AppBetaQueue-${self:provider.stage}'

functions:
  queue-processor:
    handler: packages/queue-processor/index.handler
    events:
      - sqs:
        queueName: ${self:custom.queueName}
        arn:
          Fn::GetAtt:
            - AppBetaQueue
            - Arn

resources:
  Resources:
      AppBetaQueue:
      Type: AWS::SQS::Queue
      Properties:
        QueueName: ${self:custom.queueName}
```

It seems that despite the documentation showing the standard examples of setting up the SQS event handler, only this one seems to work with this plugin:

```yaml
- sqs: arn:aws:sqs:region:XXXXXX:AppBetaQueue-dev
```

I've tried so many variations as per the standard serverless documentation but only the above works. Hopefully it's not just me having this problem!

Thanks!

**Comment by godu** [comment]
Your indentation isn't correct.

```yaml
custom:
  queueName: 'AppBetaQueue-${self:provider.stage}'

functions:
  queue-processor:
    handler: packages/queue-processor/index.handler
    events:
      - sqs:
          queueName: ${self:custom.queueName}
          arn:
            Fn::GetAtt:
              - AppBetaQueue
              - Arn

resources:
  Resources:
      AppBetaQueue:
      Type: AWS::SQS::Queue
      Properties:
        QueueName: ${self:custom.queueName}
```
