### ISSUE TITLE
Feature Idea: Enhance autoCreate to create dead letter queues and redrive policies.

### ISSUE THREAD

**Issue by tclindner** [CoorpAcademy/serverless-plugins#65]
Thank you so much for your hard work on this project! 🎉 It has made it really easy to work with SQS offline. I recently upgraded to v2. The autoCreate functionality works really well. I was able to replace a shell script that used the AWS cli to create queues. The only gap I have is dead letter queue (DLQ) support. 

Current state:
autoCreate scans the lambda event sources for SQS events. Queues are built for each event source.

Proposed state:
Optionally(?) scan the resources section to see if CloudFormation templates exist for SQS. If so, generate DLQs first then add the main queues with redrive policies. 

This may likely be outside the indented scope of this module. No worries if you aren’t interested in supporting it! 🤓

**Comment by GonzaloSaad** [comment]
Hello! Is it possible to contribute to this issue? If so, do you have any contributing guidelines?

**Comment by anaerobic** [comment]
here's a PR to allow auto-creating queues that are referenced by disabled events https://github.com/CoorpAcademy/serverless-plugins/pull/172/files

```
functions:
  doStuffAsync:
    handler: src/handlers/doStuffAsync.handler
    events:
      - sqs:
          arn:
            Fn::GetAtt:
              - FifoQueue
              - Arn
  # this is for hacking elasticmq to auto-create the queues for local development
  offlineAsync:
    handler: src/handlers/offlineAsync.handler
    events:
      - sqs:
          enabled: false
          arn:
            Fn::GetAtt:
              - DeadLetterFifoQueue
              - Arn
```

it's a little hacky, i know, but it gets the job done
