### ISSUE TITLE
after start 'arn' is undefined and not trigger the receiver function

### ISSUE THREAD

**Issue by woss** [CoorpAcademy/serverless-plugins#69]
I cannot get this module to work, it throws this error and does not trigger the Receiver function. Any idea?

yaml file:
```
service:
  name: services
  publish: false
package:
  individually: true
custom:
  stage: ${opt:stage, self:provider.stage}

  serverless-offline-sqs:
    autoCreate: true    
    apiVersion: '2012-11-05'
    endpoint: http://172.17.0.5:9324
    region: eu-west-1
    skipCacheInvalidation: false
provider:
  name: aws
  runtime: nodejs8.10
  stage: ${env:NODE_ENV}
  tracing: true # enable tracing
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "sqs:SendMessage"
        - "sqs:ListQueues"
        - "sqs:GetQueueUrl"
      Resource: "arn:aws:sqs:${self:provider.region}:*"
functions:
  ownershipDeviceSyncReceiver:
    name: ${self:custom.stage}-ownership-device-sync-from-photo-metadata
    handler: src/handlers/ownership/handler.deviceSyncFromPhotoMetadata
    reservedConcurrency: 10 <-- Concurrency control
    events:
      - sqs:
        arn:
          Fn::GetAtt:
            - LocalPhotoMetadataQueue
            - Arn
  sqsTestSender:
    name: ${self:custom.stage}-ownership-sqsTest
    handler: src/handlers/ownership/handler.testSender
    events:
      - http:
          method: post
          path: /o/sqsTest
          
plugins:
  - serverless-offline-sqs
  - serverless-offline
resources:
  Resources:
    LocalPhotoMetadataQueue:
      Type: AWS::SQS::Queue
      Properties:
        QueueName: LocalPhotoMetadataQueue
```

Error: 
```
Serverless: Offline listening on http://0.0.0.0:3000
 (node:35) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'arn' of null
     at ServerlessOfflineSQS.getQueueName (/app/node_modules/serverless-offline-sqs/src/index.js:68:27)
     at ServerlessOfflineSQS.createQueueReadable (/app/node_modules/serverless-offline-sqs/src/index.js:159:28)
     at queueEvent (/app/node_modules/serverless-offline-sqs/src/index.js:234:14)
     at r (/app/node_modules/lodash/lodash.min.js:5:356)
     at nu (/app/node_modules/lodash/lodash.min.js:67:92)
     at l (/app/node_modules/lodash/lodash.min.js:50:137)
     at mapValues.convert (/app/node_modules/serverless-offline-sqs/src/index.js:233:7)
     at /app/node_modules/lodash/lodash.min.js:101:386
     at /app/node_modules/lodash/lodash.min.js:45:502
     at mt (/app/node_modules/lodash/lodash.min.js:27:267)
     at An.mapValues (/app/node_modules/lodash/lodash.min.js:101:358)
     at l (/app/node_modules/lodash/lodash.min.js:50:137)
     at ServerlessOfflineSQS.offlineStartInit (/app/node_modules/serverless-offline-sqs/src/index.js:221:36)
```

**Comment by AdrieanKhisbe** [comment]
@woss 
If I'm not mistaked you have a mistake in your serverless:

It should be 
```
    events:
      - sqs:
          arn:
            Fn::GetAtt:
              - LocalPhotoMetadataQueue
              - Arn
```

and not 

```
    events:
      - sqs:
        arn:
          Fn::GetAtt:
            - LocalPhotoMetadataQueue
            - Arn
``
`

Indentation really matters.
See:
```js
const yaml  =require('js-yaml')
 yaml.load('a:\n- a:\n  b: 1')
// -> { a: [ { a: null, b: 1 } ]
```
