### ISSUE TITLE
[serverless-offline-sqs] Doesn't work with serverless-pseudo-parameters

### ISSUE THREAD

**Issue by maximusinc** [CoorpAcademy/serverless-plugins#74]
My serverless.yml looks like: 

```yml
plugins:
  - serverless-plugin-typescript
  - serverless-offline-sqs
  - serverless-offline
  - serverless-pseudo-parameters
# ...
functions
- processQueue:
    handler: src/handlers/processQueue.handler
    events:
      - sqs: arn:aws:sqs:${self:provider.region}:#{AWS::AccountId}:MyQueue
```

I've got an error:

```
(node:1824) UnhandledPromiseRejectionWarning: Invalid request: MissingQueryParamRejection(QueueName), MissingFormFieldRejection(QueueUrl): Invalid request: MissingQueryParamRejection(QueueName), MissingFormFieldRejection(QueueUrl); see the SQS docs.
```
Looks like pseudo parameters break realisation and queue name cannot be parsed from arn.

**Comment by tomzaku** [comment]
Mine is: Cannot find module '....../src/handler'

**Comment by matjamesymj** [comment]
@maximusinc did you ever resolve this? I have a similar issue on https://github.com/jeremydaly/serverless-cloudside-plugin/issues/4

**Comment by AdrieanKhisbe** [comment]
Some integration might have be done at some point to resolve in offline the pseudo parameter as [serverless-pseudo-parameters](https://github.com/svdgraaf/serverless-pseudo-parameters) does.

_(I reformatted your initial issue @maximusinc to have yaml syntax highlight)_

So it might need both to reverse engineer the pseudo parameters, and also resolve the values what aws cloudformation does when instantiating the stack.

I flagged the issue as _feature request_, PR are welcome :)

**Comment by sambP** [comment]
quick solution for me:

```
custom:
  accountIdOptions:
    offline: XXXXXX
    default: !Ref AWS:AccountId
  accountId: ${self:custom.accountIdOptions.${self:provider.stage}}
functions:
  processService:
    name: ${self:custom.processService}
    events:
      - sqs:
          arn: arn:aws:sqs:${self:provider.region}:${self:custom.accountId}:${self:custom.processQueue}
          batchSize: 1
```
