### ISSUE TITLE
MessageRetentionPeriod not working for serverless-offline-sqs

### ISSUE THREAD

**Issue by PhouvanhKCSV** [CoorpAcademy/serverless-plugins#87]
```
testSQS:
      Type: AWS::SQS::Queue
      Properties:
        QueueName: "my-testSQS"
        VisibilityTimeout: 25
        MessageRetentionPeriod: 120
        ReceiveMessageWaitTimeSeconds: 0
        RedrivePolicy:
          deadLetterTargetArn:
            Fn::GetAtt:
              - testDeadLetterQueue
              - Arn
          maxReceiveCount: 5

testDeadLetterQueue:
      Type: AWS::SQS::Queue
      Properties:
        QueueName: "my-testDeadLetterQueue"
        VisibilityTimeout: 25
        MessageRetentionPeriod: 120
        ReceiveMessageWaitTimeSeconds: 0
```

I have this configuration in serverless.yml, what i expected that if the message fail to process (Lamda error), it will keep trying until it reach "MessageRetentionPeriod" then it will go to "testDeadLetterQueue", it is work fine in AWS SQS (Cloud), but in local the message keep trying forever.

Could anyone suggest me what is wrong with this?
